apiVersion: v1
kind: Service
metadata:
  name: getting-started-service2
spec:
  selector:
    app: getting-started
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 5000
  type: LoadBalancer
